[package]
name = "sunshine_flow_bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sunshine_solana = { path = "../sunshine_solana" }